# Generated by Django 5.0.1 on 2024-01-12 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Overview of Course :')),
                ('description', models.TextField(blank=True, null=True)),
                ('durations', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Durations should not be nagetive')])),
                ('fees', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Fees should not be Nagetive')])),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Deactive', 'Deactive'), ('Pending', 'Pending')], max_length=55)),
            ],
        ),
    ]
